package com.guoyasoft.autoAPI.http.testCXF;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-07-29T11:31:43.648+08:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://soap.topic.guoyasoft.com/", name = "TestSoapDelegate")
@XmlSeeAlso({ObjectFactory.class})
public interface TestSoapDelegate {

    @WebMethod
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://soap.topic.guoyasoft.com/", className = "com.guoyasoft.autoAPI.http.testCXF.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://soap.topic.guoyasoft.com/", className = "com.guoyasoft.autoAPI.http.testCXF.SayHelloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
