
package com.guoyasoft.autoAPI.http.testCXF;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-07-29T11:31:43.514+08:00
 * Generated source version: 3.2.4
 *
 */
public final class TestSoapDelegate_TestSoapPort_Client {

    private static final QName SERVICE_NAME = new QName("http://soap.topic.guoyasoft.com/", "TestSoapService");

    private TestSoapDelegate_TestSoapPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TestSoapService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        TestSoapService ss = new TestSoapService(wsdlURL, SERVICE_NAME);
        TestSoapDelegate port = ss.getTestSoapPort();
        {
        System.out.println("Invoking sayHello...");
        java.lang.String _sayHello_arg0 = "23023";
        java.lang.String _sayHello_arg1 = "werwer";
        java.lang.String _sayHello__return = port.sayHello(_sayHello_arg0, _sayHello_arg1);
        System.out.println("sayHello.result=" + _sayHello__return);
        }
        System.exit(0);
    }

}
