package com.guoyasoft.autoAPI.soap;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.net.URL;

import javax.xml.namespace.QName;

import org.testng.annotations.Test;

/**
 * This class was generated by Apache CXF 3.2.4 2018-05-20T11:51:53.539+08:00
 * Generated source version: 3.2.4
 * 
 */
public final class LoginDelegate_LoginPort_Client {

	private static final QName SERVICE_NAME = new QName(
			"http://soap.guoyasoft.com/", "LoginService");

	private LoginDelegate_LoginPort_Client() {
	}

	@Test
	public void login() throws java.lang.Exception {
		URL wsdlURL = LoginService.WSDL_LOCATION;
		LoginService ss = new LoginService(wsdlURL, SERVICE_NAME);
		LoginDelegate port = ss.getLoginPort();
		{
			System.out.println("Invoking checkUser...");
			java.lang.String _checkUser_arg0 = "guoya";
			com.guoyasoft.autoAPI.soap.Response response = port
					.checkUser(_checkUser_arg0);
			System.out.println("checkUser.result=" + response.getRespCode()
					+ "," + response.getRespDesc());
		}
	}

}
