package com.guoyasoft.autoAPI.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-20T11:51:53.673+08:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://soap.guoyasoft.com/", name = "LoginDelegate")
@XmlSeeAlso({ObjectFactory.class})
public interface LoginDelegate {

    @WebMethod
    @RequestWrapper(localName = "checkUser", targetNamespace = "http://soap.guoyasoft.com/", className = "com.guoyasoft.soap.CheckUser")
    @ResponseWrapper(localName = "checkUserResponse", targetNamespace = "http://soap.guoyasoft.com/", className = "com.guoyasoft.soap.CheckUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.guoyasoft.autoAPI.soap.Response checkUser(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
